language: nix

sudo: false

os:
  - linux

# Deploying requires checkout out other branches and pushing commits.
git:
  depth: false

branches:
  only:
    - main

script:
  - nix-shell --command "./bin/deploy"
