name: "Publish"

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
      - run: nix-shell --command "jank-deploy"
